accounts/urls.py
from django.urls import path, include
from . import views


app_name = 'accounts'

urlpatterns = [
    path('', views.profile_complete, name='profile_complete'),
    path('auth/', include('django.contrib.auth.urls')),
    # register path is archived since we're using allauth'
    # path('register/', views.register, name='register'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('groups/', views.GroupListView.as_view(), name='groups'),
    path('user-requests/', views.user_requests_list, name='user_requests'),
    path('permission-error/', views.permission_error, name='permission_error'),
    path('approval/<int:pk>/<int:approved>',views.user_approval, name='user_approval'),
    path('modify-and-approve/<int:pk>/',views.user_approval_with_modification,name='approval_with_modification'),
    path('user/<int:pk>/change', views.UserUpdateView.as_view(), name='user_change'),
    path('api/upload-profile-picture', views.profile_picture_upload,name='profile_picture_upload'),
]

pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
     path('', views.index, name='landing'),
     path('admission/', views.online_admission, name='online_admission'),
     path('admission/payment/<int:pk>/', views.online_admission_payment,
          name='online_admission_payment'
     ),
     path('admission/paynow/<int:pk>/', views.payment,
          name='payment'
     ),
     path('userguide/', views.user_guide_view,
          name='userguide'
     ),
]

school_web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

from institute.models import InstituteProfile
from accounts.views import dashboard

try:
    institute = InstituteProfile.objects.get(active=True)
    admin.site.site_header = institute.site_header
    admin.site.site_title = institute.site_title
    admin.site.index_title = institute.index_title
except:
    admin.site.site_header = 'Django Administration'
    admin.site.site_title = 'Django Site Admin'
    admin.site.index_title = 'Django Administration'

DJANGO_ADMIN_URL = settings.DJANGO_ADMIN_URL + '/'

urlpatterns = [
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path(DJANGO_ADMIN_URL, admin.site.urls),
    path('', include('pages.urls')),
    path('dashboard/', dashboard, name='index_view'),
    path('accounts/', include('allauth.urls')),
    path('blog/', include('articles.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('account/', include('accounts.urls')),
    path('academics/', include('academics.urls')),
    path('students/', include('students.urls')),
    path('teachers/', include('teachers.urls')),
    path('result/', include('result.urls')),
    path('institute/', include('institute.urls')),
    path('password-reset/',
        auth_views.PasswordResetView.as_view(
            template_name='account/password/password_reset.html'
        ),
        name="password_reset",
    ),
    path('password_reset/done/',
        auth_views.PasswordResetDoneView.as_view(
            template_name='account/password/password_reset_done.html'
        ),
        name="password_reset_done",
    ),
    path('password-reset-confirm/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='account/password/password_reset_confirm.html'
        ),
        name='password_reset_confirm',
    ),
    path('password-reset-complete/',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='account/password/password-reset-complete.html'
        ),
        name='password_reset_complete'
    ),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                            document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                            document_root=settings.STATIC_ROOT)

if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [
            path("__debug__/", include(debug_toolbar.urls))
        ] + urlpatterns

accounts/models.py
# Create your models here.
from django.contrib.auth.models import AbstractUser
from ckeditor_uploader.fields import RichTextUploadingField
from django_countries.fields import CountryField
from django.db import models
from django.db.models.signals import pre_save
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import Group
from django.conf import settings
from django.urls import reverse


class User(AbstractUser):
    REQUESTED_ACCOUNT_TYPE_CHOICES = (
        ('subscriber', 'Subscriber'),
        ('student', 'Student'),
        ('teacher', 'Teacher'),
        ('editor', 'Editor'),
        ('academic_oficer', 'Academic Officer'),
        ('admin', 'Admin'),
    )
    APPROVAL_CHOICES = (
        ('n', 'Not Requested For Approval'),
        ('p', 'Approval Application on Pending'),
        ('d', 'Approval Request Declined'),
        ('a', 'Verified')
    )
    approval_status = models.CharField(max_length=2,choices=APPROVAL_CHOICES,default='n',)
    employee_or_student_id = models.CharField(max_length=10,blank=True, null=True)
    requested_role = models.CharField(
        choices=REQUESTED_ACCOUNT_TYPE_CHOICES,
        max_length=50,
        default=REQUESTED_ACCOUNT_TYPE_CHOICES[0][0]
    )
    approval_extra_note = models.TextField(blank=True, null=True)

    def get_author_url(self):
        return reverse(
            'articles:author_profile',
            args=[self.username,])


class CustomGroup(Group):
    group_creator = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)

    def display_group(self):
        return f'{self.name} created by {self.group_creator}'


class SocialLink(models.Model):
    user_profile = models.ForeignKey('CommonUserProfile',on_delete=models.CASCADE)
    media_name = models.CharField(max_length=50)
    url = models.URLField()

    def __str__(self):
        return self.media_name


class CommonUserProfile(models.Model):
    user = models.OneToOneField(User,related_name='profile',on_delete=models.SET_NULL,null=True)
    profile_picture = models.ImageField(upload_to='profile-pictures',blank=True,null=True)
    cover_picture = models.ImageField(upload_to='cover-pictures',blank=True,null=True)
    headline = models.CharField(max_length=255,blank=True,null=True)
    show_headline_in_bio = models.BooleanField(help_text='I want to use this as my bio',default=False)
    summary = RichTextUploadingField(help_text='Your Profile Summary',blank=True,null=True)
    country = CountryField(blank=True,null=True)
    social_links = models.ManyToManyField(SocialLink,related_name='social_links',blank=True
    )

    class Meta:
        verbose_name = 'User Profile'
        verbose_name_plural = 'User Profiles'

    def __str__(self):
        return f'{self.user}\'s profile'

accounts/views.py
from rolepermissions.roles import assign_role
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import user_passes_test, login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import ListView
from django.views.generic.edit import UpdateView
from django.urls import reverse

from academics.models import Department
from students.models import Student
from teachers.models import Teacher
from .forms import (
    UserRegistrationForm,
    ProfileCompleteForm,
    ApprovalProfileUpdateForm,
    UserChangeFormDashboard
)
from .models import CustomGroup, User
from .forms import (CommonUserProfileForm,
    UserProfileSocialLinksFormSet
)
from permission_handlers.administrative import (
    user_is_admin_or_su, user_editor_admin_or_su
)
from permission_handlers.basic import user_is_verified, permission_error


@login_required(login_url='account_login')
def profile_complete(request):
    ctx = {}
    user = User.objects.get(pk=request.user.pk)

    try:
        profile_edit_form = CommonUserProfileForm(
            instance=user.profile
        )
        social_links_form = UserProfileSocialLinksFormSet(
            instance=user.profile
        )
        ctx.update({
            'profile_edit_form': profile_edit_form,
            'social_links_form': social_links_form
        })
    except:
        messages.add_message(
            request,
            messages.INFO,
            "Maybe your account is not verified yet, please check your badge."
        )

    verification_form = ProfileCompleteForm(instance=user)
    if request.method == 'POST':
        verification_form = ProfileCompleteForm(
            request.POST,
            instance=user
        )
        if 'user-profile-update-form' in request.POST:
            profile_edit_form = CommonUserProfileForm(
                request.POST,
                request.FILES,
                instance=user.profile
            )
            social_links_form = UserProfileSocialLinksFormSet(
                request.POST,
                instance=user.profile
            )
            if profile_edit_form.is_valid():
                profile_edit_form.save()

            if social_links_form.is_valid():
                social_links_form.save()
            
            messages.add_message(
                request,
                messages.SUCCESS,
                'Your profile has been saved.'
            )
            return redirect('account:profile_complete')
        else:
            if verification_form.is_valid():
                verification_form.instance.approval_status = 'p'
                # approval status get's pending
                verification_form.save()
                messages.add_message(
                    request,
                    messages.SUCCESS,
                    'Your request has been sent, please be patient.'
                )
                return redirect('account:profile_complete')
    user_permissions = user.user_permissions.all()
    ctx.update({
        'verification_form': verification_form,
        'user_perms': user_permissions if user_permissions else None,
    })
    return render(request, 'account/profile_complete.html', ctx)


@user_passes_test(
    user_editor_admin_or_su,
    login_url='account:profile_complete')
def dashboard(request):
    total_students = Student.objects.count()
    total_teachers = Teacher.objects.count()
    total_departments = Department.objects.count()
    context = {
        'total_students': total_students,
        'total_teachers': total_teachers,
        'total_departments': total_departments,
    }
    return render(request, 'dashboard.html', context)


@user_passes_test(user_is_admin_or_su, login_url='account:permission_error')
def user_approval(request, pk, approved):
    """ Approve or decline approval request based on parameter `approved`.
    approved=0 means decline, 1 means approve.
    """
    user = User.objects.get(pk=pk)
    requested_role = user.requested_role

    if approved:
        assign_role(user, requested_role)
        if requested_role == 'admin':
            user.is_staff = True
        user.approval_status = 'a'
        user.save()
        messages.add_message(
            request,
            messages.SUCCESS,
            f'{user}\'s account has been approved.'
        )
    else:
        messages.add_message(
            request,
            messages.SUCCESS,
            f'{user}\'s request for {requested_role} has been declined.'
        )
    return redirect('account:user_requests')


@user_passes_test(user_is_admin_or_su, login_url='account:permission_error')
def user_approval_with_modification(request, pk):
    user = User.objects.get(pk=pk)
    form = ApprovalProfileUpdateForm()
    if request.method == 'POST':
        requested_role = request.POST.get('requested_role')
        assign_role(user, requested_role)
        if requested_role == 'admin':
            user.is_staff = True
        user.approval_status = 'a'
        user.save()
        messages.add_message(
            request,
            messages.SUCCESS,
            f'{user}\'s account has been approved.'
        )
        return redirect('account:user_requests')
    ctx = {
        'form': form,
    }
    return render(request, 'account/modify_approval.html', ctx)


# THIS IS ARCHIVED, SINCE WE'RE USING ALLAUTH
# def register(request):
#     if request.method == 'POST':
#         user_form = UserRegistrationForm(request.POST)
#         if user_form.is_valid():
#             new_user = user_form.save(commit=False)
#             new_user.set_password(
#                 user_form.cleaned_data['password1'])
#             new_user.save()
#             auth_user = authenticate(
#                 username=user_form.cleaned_data['username'],
#                 password=user_form.cleaned_data['password1']
#             )
#             if auth_user is not None:
#                 login(request, auth_user)
#             if auth_user.is_staff:
#                 return redirect('account:dashboard')
#             else:
#                 return redirect('account:profile_complete')
#         else:
#             return render(request, 'account/register.html', {'user_form': user_form})

#     else:
#         user_form = UserRegistrationForm()
#         return render(request, 'account/register.html', {'user_form': user_form})


class AccountListView(LoginRequiredMixin, UserPassesTestMixin, ListView):
    model = User
    template_name = 'account/dashboard/accounts_list.html'
    context_object_name = 'accounts'

    def test_func(self):
        user =  self.request.user
        return user_is_verified(user)

    def handle_no_permission(self):
        if self.request.user.is_authenticated:
            return redirect('account:profile_complete')
        return redirect('account_login')



class GroupListView(LoginRequiredMixin, UserPassesTestMixin, ListView):
    model = CustomGroup
    template_name = 'academics/group_list.html'
    context_object_name = 'groups'

    def test_func(self):
        user =  self.request.user
        return user_is_verified(user)

    def handle_no_permission(self):
        if self.request.user.is_authenticated:
            return redirect('account:profile_complete')
        return redirect('account_login')


class UserRequestsListView(LoginRequiredMixin, UserPassesTestMixin,ListView):
    queryset = User.objects.exclude(approval_status='a')
    template_name = 'account/user_requests.html'
    context_object_name = 'users'

    def test_func(self):
        user =  self.request.user
        return user_is_admin_or_su(user)

user_requests_list = UserRequestsListView.as_view()


def profile_picture_upload(request):
    """
    Handles profile pic uploads coming through ajax.
    """
    if request.method == 'POST':
        image = request.FILES.get('profile-picture')
        try:
            request.user.profile.profile_picture = image
            request.user.profile.save()
            return JsonResponse({
                'status': 'ok',
                'imgUrl': request.user.profile.profile_picture.url,
            })
        except:
            return JsonResponse({'status': 'error'})


class UserUpdateView(UpdateView):
    form_class = UserChangeFormDashboard
    queryset = User.objects.all()
    template_name = 'account/dashboard/update_user.html'

    def get_success_url(self):
        return reverse(
            'articles:author_profile',
            args=[self.object.username,])

accounts/templates/accounts/login.html
{% load widget_tweaks %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Login</title>
    <link
      href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css"
      rel="stylesheet"
    />
  </head>
  <body>
    <div
      class="min-h-screen flex items-center justify-center bg-gray-50 py-12 px-4 sm:px-6 lg:px-8"
    >
      <div class="max-w-md w-full space-y-8">
        <!-- Topbar messages -->
        <div>
          <img
            class="mx-auto h-12 w-auto"
            src="{{ request_institute.logo.url }}"
            alt="{{ request_institute.name }}"
          />
          <h2 class="mt-6 text-center text-3xl font-extrabold text-gray-900">
            Sign in to your account
          </h2>
          <p class="mt-2 text-center text-sm text-gray-600">
            Or
            <a
              href="{% url 'account_signup' %}"
              class="font-medium text-indigo-600 hover:text-indigo-500"
            >
              create a new account
            </a>
          </p>
        </div>
        <form class="mt-8 space-y-6" action="" method="POST">
          {% csrf_token %} 
          {% for hidden_field in form.hidden_fields %}
            {{ hidden_field.errors }}
            {{ hidden_field }}
          {% endfor %}

          
          <!-- <input type="hidden" name="remember" value="true" /> -->
          <div class="rounded-md shadow-sm -space-y-px">
            {% for field in form.visible_fields %}
              {% if not field.name == 'remember' %}
              <div class="mb-4">
                {{ field.label_tag }}
                <small class="text-muted">{{ field.errors }}</small>
                {% render_field field class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm" placeholder=field.name %}
              </div>
              {% elif field.name == 'remember' %}
              <!-- Recovery and login link -->
              <div class="flex items-center justify-between mt-4">
                <div class="flex items-center mt-5">
                  {% render_field field class="h-4 w-4 text-indigo-600 focus:ring-indigo-500 border-gray-300 rounded" %}
                  <label for="remember_me" class="ml-2 block text-sm text-gray-900">
                    Remember me
                  </label>

                  <!-- Show password -->
                  <input class="ml-3 h-4 w-4 text-indigo-600 focus:ring-indigo-500 border-gray-300 rounded" type="checkbox" onclick="showPassword()">
                  <label class="ml-1 block text-sm text-gray-900">
                    Show Password
                  </label>
                </div>

                <div class="text-sm">
                  <a
                    href="{% url 'account_reset_password' %}"
                    class="font-medium text-indigo-600 hover:text-indigo-500"
                  >
                    Forgot your password?
                  </a>
                </div>
              </div>
              {% endif %}
            {% endfor %}
          </div>

          <!-- Submit Button -->
          <div>
            <button
              type="submit"
              class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
            >
              <span class="absolute left-0 inset-y-0 flex items-center pl-3">
                <!-- Heroicon name: lock-closed -->
                <svg
                  class="h-5 w-5 text-indigo-500 group-hover:text-indigo-400"
                  xmlns="http://www.w3.org/2000/svg"
                  viewBox="0 0 20 20"
                  fill="currentColor"
                  aria-hidden="true"
                >
                  <path
                    fill-rule="evenodd"
                    d="M5 9V7a5 5 0 0110 0v2a2 2 0 012 2v5a2 2 0 01-2 2H5a2 2 0 01-2-2v-5a2 2 0 012-2zm8-2v2H7V7a3 3 0 016 0z"
                    clip-rule="evenodd"
                  />
                </svg>
              </span>
              Sign in
            </button>
          </div>
        </form>
      </div>
    </div>


    <script>
      function showPassword() {
        var passwordInput = document.getElementById("id_password");
        if (passwordInput.type === "password") {
          passwordInput.type = "text";
        } else {
          passwordInput.type = "password";
        }
      } 
    </script>
  </body>
</html>

accounts/templates/accounts/modify_approval.html
{% extends 'dashboard.html' %}
{% load static %}
{% load crispy_forms_tags %} 

{% block dashboard-body %} 
<div class="container">
  {% if messages %} 
      {% for message in messages %}
      <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
      <strong>{{ message }}</strong>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
      </button>
      </div>
      {% endfor %} 
  {% endif %}
  <form
    action="."
    method="POST"
    class="admission-form d-block"
  >
    {% csrf_token %} {{ form|crispy }}
    <input type="submit" value="Approve" class="btn btn-dark" />
  </form>
</div>
{% endblock %}

{% block extrajs %}
  <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
{% endblock %}

accounts/templates/accounts/profile_complete.html
{% extends 'website/partials/website_base.html' %} 
{% load static %} 
{% load crispy_forms_tags %} 

{% block extra_css %}
  <style type="text/css">
    #profile-edit-form .multiField:not(:last-child) {
      border-bottom: 1px solid #e1e1e1;
    }
    @media screen 
      and (min-device-width: 1200px) 
      and (max-device-width: 1600px) { 
        #profile-edit-form .multiField {
        display: flex;
        justify-content: space-between;
        align-items: center;
      }
    }
  </style>
{% endblock extra_css %}
  

{% block main_content %}
<!-- Header Section Start -->
<header id="home" class="mt-5">
  {% include 'website/partials/website_navbar.html' %}
</header>

<!-- section profile detail -->
<section id="profile" class="profile-section py-5">
  <div class="container">
    <div class="row">
      <!-- profile card -->
      <div class="col-md-4">
        <div class="card text-center">
          <div class="card-header">{{ user.get_approval_status_display }}</div>
          <div class="card-body d-flex">
            <form action="{% url 'account:profile_picture_upload' %}" 
            method="post" id="profile-image-form"
            enctype="multipart/form-data">
              {% csrf_token %}
              <input id="profile-image-upload" class="hidden w-25 d-none" type="file"
              name="profile-picture">
              <img id="profile-image"
              {% if user.profile.profile_picture %}
                src="{{ user.profile.profile_picture.url }}" 
              {% else %}
                src=""
              {% endif %}
              width="150" />
            </form>
            <div class="card-text align-self-end ml-3">
              <div class="text-left">
                <h6 class="mb-0">
                  <span>{{ request.user.username }}</span>
                  <span class="small text-dark"
                    style="cursor: pointer;"
                    data-toggle="modal" 
                    data-target="#request-update-modal">
                    <span id="update-verification-icon"
                      title="Update Verification Request">
                      <i class="fas fa-cog"></i>
                    </span>
                  </span>
                </h6>
                {% if user.approval_status == 'a'%}
                  <small>({{ request.user.requested_role }})</small>
                {% endif %}
                <small>
                  {{ request.user.email|default:"Please, add your email address" }}
                </small>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Profile Complete Form -->
      <div class="col-md-8">
        <div class="card p-3">
          {% if user.approval_status != 'a' %}
          <div class="alert alert-warning" role="alert">
            Your profile is not verified yet, please verify your account.
          </div>
          {% endif %} 
          
          {% if messages %} 
            {% for message in messages %}
              <div
                class="alert {{ message.tags }} alert-dismissible fade show"
                role="alert"
              >
                <strong>{{ message }}</strong>
                <button
                  type="button"
                  class="close"
                  data-dismiss="alert"
                  aria-label="Close"
                >
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
            {% endfor %} 
          {% endif %} 
          
          <!-- Form for UnVerified User (SENDS A VERIFICATION REQUEST) -->
          {% if user.approval_status != 'a' %}
            <form method="post">
              <div
                class="alert alert-warning alert-dismissible fade show"
                role="alert"
              >
                <strong>Your account is not verified.</strong>
                <button
                  type="button"
                  class="close"
                  data-dismiss="alert"
                  aria-label="Close"
                >
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
          {% else %}
            <!-- Form for verfied users (UPDATES USER PROFILE DETAILS) -->
            <form action="" method="POST" 
              enctype="multipart/form-data"
              id="profile-edit-form"
            >
              {% csrf_token %}
              <div class="card-header">
                General Information
              </div>
              <div class="">
                {% if not profile_not_found %}
                  {{ profile_edit_form|crispy }}
                  <hr>
                  <div class="card-header">Social Links</div>
                  {{ social_links_form|crispy }}
                {% else %}
                  <div class="alert alert-warning" role="alert">
                    {{ profile_not_found }}
                  </div>
                {% endif %}
                <input type="submit" value="Save Changes"
                  class="btn btn-secondary float-right mt-3
                  shadow"
                  name="user-profile-update-form">
              </div>
          </form>
          {% endif %}
        </div>

        {% if user_perms %}
          <div class="card p-3 mt-5">
            <div class="card-header">
              My Permissions
            </div>
            <div class="card-body">
              {% for permission in user_perms %}
              <div>{{ permission }}</div>
              {% endfor %}
            </div>
          </div>
         {% endif %}
      </div>
    </div>
  </div>
</section>


<div class="modal fade" 
  id="request-update-modal" tabindex="-1" 
  role="dialog" 
  aria-hidden="true">
  <form action="{% url 'account:profile_complete' %}" method="post">
    {% csrf_token %}
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h6 class="" id="">
            Change Profile Verification
          </h6>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          {{ verification_form|crispy }}
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Save changes</button>
        </div>
      </div>
    </div>
  </form>
</div>
{% endblock %}

{% block extra_js %}
<script>

  // get csrf token (provided by django)
  function getCookie(name) {
      let cookieValue = null;
      if (document.cookie && document.cookie !== '') {
          const cookies = document.cookie.split(';');
          for (let i = 0; i < cookies.length; i++) {
              const cookie = cookies[i].trim();
              // Does this cookie string begin with the name we want?
              if (cookie.substring(0, name.length + 1) === (name + '=')) {
                  cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                  break;
              }
          }
      }
      return cookieValue;
  }
  const csrftoken = getCookie('csrftoken');

  // profile picture upload
  $('#profile-image').on('click', function() {
    $('#profile-image-upload').click();
  });

  $('#profile-image-form').on('submit', function(e) {
    e.preventDefault();
    const formData = new FormData($('#profile-image-form').get(0));
    console.log(formData);
    $.ajax({
      type: 'POST',
      url: $(this).attr('action'),
      data: formData,
      cache: false,
      processData: false,
      contentType: false,
      csrfmiddlewaretoken: csrftoken,
      success: function (data) {
        const imageUrl = data.imgUrl;
        $('#profile-image').attr('src', imageUrl);
      },
      error: function (data) {
        console.log("error");
        console.log(data);
      }
    })
  })

  $('#profile-image-upload').on('change', function() {
    $('#profile-image-form').submit();
  })

</script>
{% endblock %} 

accounts/templates/accounts/user_requests.html
{% extends 'dashboard.html' %}
{% load static %} 

{% block dashboard-body %}
<div class="container-fluid">
  <h1>USER REQUESTS</h1>

  {% if messages %} 
      {% for message in messages %}
      <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
      <strong>{{ message }}</strong>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
      </button>
      </div>
      {% endfor %} 
  {% endif %}

  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Email</th>
        <th scope="col">Approval Status</th>
        <th scope="col">Requested Role</th>
        <th scope="col">Approval Action</th>
      </tr>
    </thead>
    <tbody>
      {% for user in users %}
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{ user }}</td>
        {% with req_role=user.approval_status %}
          <td class="{% if req_role == 'd' %}bg-warning{% endif %}">
            {{ user.get_approval_status_display }}
          </td>
        {% endwith %}
        <td>{{ user.get_requested_role_display }}</td>
        <td>
          <a href="{% url 'account:user_approval' pk=user.pk approved=1 %}"
            class="btn btn-sm btn-success approve"
            data-user-pk="{{ user.pk }}">
            Aprove
          </a>
          <a 
            href="{% url 'account:approval_with_modification' pk=user.pk %}" 
            class="btn btn-sm btn-primary approve"
            data-user-pk="{{ user.pk }}">
            Modify & Approve
          </a>
          <a href="{% url 'account:user_approval' pk=user.pk approved=0 %}" 
            class="btn btn-sm btn-danger">
            Decline
          </a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock dashboard-body %}

{% block extrajs %}
<script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
{% endblock %}